spring:
  profiles:
    active: local

###############
## Local 환경 #
###############
---
spring:
  profiles: local

  #  datasource:
#    hikari:
#      jdbc-url: jdbc:mariadb://my-mariadb.mariadb.database.azure.com:3306/project_v?useSSL=true&characterEncoding=UTF-8&serverTimezone=UTC
#      driver-class-name: org.mariadb.jdbc.Driver
#      username: ENC(fHF03FbnN1R4+d8WE/zymLu4lEcUImRZ90pHZc1HS/U=)
#      password: ENC(2SYD7hl0pZ9zdWbviKMpOBbhShHIpo8J)
  datasource:
    url: jdbc:h2:tcp://localhost/~/dev/h2/database/projectv
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  cache:
    jcache:
      config: classpath:config/ehcache.xml

logging.level:
  org.hibernate.SQL: debug

jasypt:
  encryptor:
    bean: jasyptStringEncrptor

svn:
  tempDir: C:\Users\MJ\dev\temp