spring:
  profiles:
    active: local

encrypt:
  key: testKey
  algorithm: PBEWithMD5AndDES
  salt: 1234

jwt:
  key: sibal

###########################################################################
############################### Local 환경 #################################
###########################################################################
---
spring:
  profiles: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/dev/h2/database/projectv
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  cache:
    jcache:
      config: classpath:config/ehcache.xml

logging.level:
  org.hibernate.SQL: debug

jasypt:
  encryptor:
    bean: jasyptStringEncryptor


###########################################################################
############################### Dev 환경 #################################
###########################################################################
---
spring:
  profiles: dev

  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://my-mariadb.cpmmhoavnmru.ap-northeast-2.rds.amazonaws.com:3306/projectv
      driver-class-name: org.mariadb.jdbc.Driver
      username: ENC(fCJAfjkw/K/Ye/OrBHFnOnginV/7mT2V)
      password: ENC(LUeqX2JCP6IBGe9dq+snYThg0IR4DYIVEn0Jt5vwwxs=)

  jpa:
    hibernate:
      ddl-auto: none      # 건들이지 말 것
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  cache:
    jcache:
      config: classpath:config/ehcache.xml

logging.level:
  org.hibernate.SQL: info

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
