# projectv-backend.yml

name: projectv-backend

on:
  workflow_dispatch:

# env:
#   ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
#   ENCRYPT_ALGORITHM: ${{ secrets.ENCRYPT_ALGORITHM }}
#   ENCRYPT_SALT: ${{ secrets.ENCRYPT_SALT }}
#   JWT_KEY: ${{ secrets.JWT_KEY }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        
      - name: Create encrypt properties file
        shell: bash
        run: echo -e "encrypt.key=testkey\nencrypt.algorithm=PBEWithMD5AndDES\nencrypt.salt=ABCD\njwt.key=testjwtkey" > ./src/main/resources/encrypt.properties
        
                
      - name: Build with Gradle
#         env:
#           encypt.key: testkey
#           encrypt.algorithm: PBEWithMD5AndDES
#           encrypt.salt: ABCD
#           jwt.key: testjwtkey
        run: ./gradlew clean build -Dfile.encoding=UTF-8
        shell: bash
