# projectv-backend.yml

name: projectv-backend

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        
      - name: Create encrypt properties file
        run: echo -e "encypt.key=$ENCRYPT_KEY\nencrypt.algorithm=$ENCRYPT_ALGORITHM\nencrypt.salt=$ENCRYPT_SALT\njwt.key=$JWT_KEY"
        shell: bash
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
          ENCRYPT_ALGORITHM: ${{ secrets.ENCRYPT_ALGORITHM }}
          ENCRYPT_SALT: ${{ secrets.ENCRYPT_SALT }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
        
      - name: Build with Gradle
        run: ./gradlew clean build -Dfile.encoding=UTF-8
        shell: bash
